### ISSUE TITLE
🐞 - 

### ISSUE THREAD

**Issue by dennitorf** [hakimio/ngx-ui-tour#143] opened 2023-08-24 14:54 UTC
### Which ngx-ui-tour-* package is the source of the bug?

md-menu

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-wau2z8?file=src%2Fapp%2Fui-tour-demo.component.ts

### Description

After install the library in an Angular project with Angular@15, I'm facing issues like below:

Error: node_modules/ngx-ui-tour-ngx-bootstrap/lib/tour-anchor.directive.d.ts:26:100 - error TS2344: Type '{ tourAnchor: { alias: "tourAnchor"; required: false; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
  Property '"tourAnchor"' is incompatible with index signature.
    Type '{ alias: "tourAnchor"; required: false; }' is not assignable to type 'string'.

26     static ɵdir: i0.ɵɵDirectiveDeclaration<TourAnchorNgxBootstrapDirective, "[tourAnchor]", never, { "tourAnchor": { "alias": "tourAnchor"; "required": false; }; }, {}, never, never, true, never>;

Could you ls advice how to fix it?

### Angular version

15.2.0

### Ngx UI Tour version

latest

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by hakimio** [comment] 2023-08-24 18:40
Latest version of the library is for Angular 16. You should use `v10` with Angular 15.

**Comment by dennitorf** [comment] 2023-08-24 18:41
Hi @hakimio , 

Thanks, I'll try and confirm. Thanks.

**Comment by hakimio** [comment] 2023-08-24 18:51
You have to provide more information. 
What TypeScript and ngx-bootstrap version are you using? 
What's the code giving you this error? 
Can you reproduce the issue in a new Angular project?

**Comment by hakimio** [comment] 2023-08-24 18:52
Also, please fill the bug report form properly. The form is there for a reason.

**Comment by dennitorf** [comment] 2023-08-24 18:55
Hi @hakimio , 

Thanks for your comments. 

"ngx-bootstrap": "^11.0.2",
 "ngx-ui-tour-ngx-bootstrap": "^10.6.0",

Typescript 

"typescript": "~4.9.4"

What's the code giving you this error? - while execution ng serve

Can you reproduce the issue in a new Angular project? - I'll try and confirm. 

Thanks,

**Comment by hakimio** [comment] 2023-08-24 19:19
`ngx-bootstrap` `v11` is also for Angular `16`. `v10` is for Angular `15`.
I imagine you have some messed up dependencies. Make sure you are using all correct library versions for your Angular version.

**Comment by dennitorf** [comment] 2023-08-28 17:49
Hi @hakimio , 

Thanks for your help. Indeed, it was related to a depencies problem. I started to use the suggested versions and the issue was cleared. 

Thanks,

**Comment by hakimio** [comment] 2023-08-29 07:43
Closing since it seems you have found solution to your issue.

**Closed by hakimio** 2023-08-29 07:43 UTC
Labels: bug, needs-triage
