### ISSUE TITLE
Angular 14: peer dependencies

### ISSUE THREAD

**Issue by JulienBier** [hakimio/ngx-ui-tour#70] opened 2022-08-08 17:52 UTC
Hi, 

I've updated to Angular 14 and everything seems ok but I encountered a peer dependency issue in npm.

```npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: ngx-ui-tour-core@8.1.2
npm ERR! Found: @angular/common@14.1.1
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^14.1.1" from the root project
npm ERR!   peer @angular/common@"^14.0.0 || ^15.0.0" from @angular/cdk@14.1.1
npm ERR!   node_modules/@angular/cdk
npm ERR!     @angular/cdk@"^14.1.1" from the root project
npm ERR!   6 more (@angular/forms, @angular/platform-browser, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">=12.0.0 <14.0.0" from ngx-ui-tour-core@8.1.2
npm ERR! node_modules/ngx-ui-tour-core
npm ERR!   ngx-ui-tour-core@"^8.1.2" from the root project
npm ERR!   ngx-ui-tour-core@"8.1.2" from ngx-ui-tour-ngx-bootstrap@8.1.2
npm ERR!   node_modules/ngx-ui-tour-ngx-bootstrap
npm ERR!     ngx-ui-tour-ngx-bootstrap@"^8.1.2" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/common@13.3.11
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@">=12.0.0 <14.0.0" from ngx-ui-tour-core@8.1.2
npm ERR!   node_modules/ngx-ui-tour-core
npm ERR!     ngx-ui-tour-core@"^8.1.2" from the root project
npm ERR!     ngx-ui-tour-core@"8.1.2" from ngx-ui-tour-ngx-bootstrap@8.1.2
npm ERR!     node_modules/ngx-ui-tour-ngx-bootstrap
npm ERR!       ngx-ui-tour-ngx-bootstrap@"^8.1.2" from the root project```

In the ngx-ui-tour-core package,json, the peer dependencies require angular 12 or 13 :

```  "peerDependencies": {
    "@angular/common": ">=12.0.0 <14.0.0",
    "@angular/core": ">=12.0.0 <14.0.0",
    "@angular/router": ">=12.0.0 <14.0.0",
    "rxjs": ">=6.0.0",
    "typescript": ">=3.8.0"
  },
```

Could you update the dependencies to make the library full compatible with angular 14 ?

Thanks you.

**Comment by hakimio** [comment] 2022-08-08 20:27
Duplicate of #63 
I'll take a look at this and some other issues sometime this month when I have time.
For now you can either force the dependencies when using npm or use yarn instead which will only give you a warning.

**Closed by hakimio** 2022-08-08 20:27 UTC
