### ISSUE TITLE
🐞 - [Ionic] Unable to use side:"top" placement

### ISSUE THREAD

**Issue by selected-pixel-jameson** [hakimio/ngx-ui-tour#130] opened 2023-05-31 15:52 UTC
### Which ngx-ui-tour-* package is the source of the bug?

ngx-ui-tour-ionic

### Description

I'm trying to adjust my popovers placement by using `placement: { alignment: "center", side: "top" }`, but the popovers are just showing over the top of the anchor and not above it. When I don't set a custom value for the 'side' property the popover works fine, but I need it to appear above the element. 

![Screenshot 2023-05-31 at 10 46 55 AM](https://github.com/hakimio/ngx-ui-tour/assets/28204537/d023cf23-aceb-4879-a85a-884eec877966)
![Screenshot 2023-05-31 at 10 47 23 AM](https://github.com/hakimio/ngx-ui-tour/assets/28204537/f4d9329d-382b-44cb-8501-abe0cd395b94)

### Angular version

15+

### Ngx UI Tour version

"ngx-ui-tour-ionic": "^1.7.0",

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [X] Android

**Comment by hakimio** [comment] 2023-06-02 12:24
Is ionic `ion-popover` positioned correctly with the same options?

**Comment by selected-pixel-jameson** [comment] 2023-06-02 12:38
@hakimio Apparently not. The arrow doesn't seem to show either when I use "side":"top". Interesting because as far as I'm aware I'm not applying any custom style to the popovers.

**Comment by hakimio** [comment] 2023-06-02 12:42
Maybe you should create a bug report in ionic repo then if you can create a reproduction for this issue outside of your app?

**Comment by hakimio** [comment] 2023-06-21 14:20
Closing since it seems to be Ionic issue.

**Closed by hakimio** 2023-06-21 14:20 UTC
Labels: invalid

**Comment by hakimio** [comment] 2023-09-07 08:24
The ionic popover bug seems to be fixed in [v7.3.3](https://github.com/ionic-team/ionic-framework/releases/tag/v7.3.3).
